name: cp_repository
description: A Competitive Programming problem tracker
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.0 
  url_launcher: ^6.1.11
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/images/
  uses-material-design: true

flutter_icons:
  android: true
  image_path: assets/images/logo.png